// examples/solid/pages/index/+Page.tsx
import { createSignal } from 'solid-js';
import ShadowRoot from '@declarative-shadow-dom/solid';

export default function Page() {
  const [count, setCount] = createSignal(0);

  return (
    <>
      <div>
        <ShadowRoot>
          <button onClick={() => setCount((c) => c - 1)}>-</button>
          <slot></slot>
          <button onClick={() => setCount((c) => c + 1)}>+</button>
        </ShadowRoot>

        {count()}
      </div>
    </>
  );
}

// examples/react/app/routes/_index.tsx
import { useState } from "react";
import ShadowRoot from "@declarative-shadow-dom/react";

function App() {
	const [count, setCount] = useState(0);

	return (
		<>
			<div>
				<ShadowRoot>
					<button onClick={() => setCount((c) => c - 1)}>-</button>
					<slot></slot>
					<button onClick={() => setCount((c) => c + 1)}>+</button>
				</ShadowRoot>

				{count}
			</div>
		</>
	);
}

export default App;
